screen_h = 1572
window_maximized = false
screen_w = 3024
language = zh_CN
server_announce = false
enable_damage = true
creative_mode = false
maintab_LAST = local
menu_last_game = minetest

# ===== 性能优化 =====

# ===== UI 缩放 =====
mainmenu_last_selected_world = 1
